### ISSUE TITLE
READ & WRITE ACCESS(PIYUSH RAI EMP CODE-3879)- AccelPro VPN Access Required

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-VPN#1]
Kindly let me have Accel Pro ID & Passoword for using the system from Home Wi-fi. I have Newly Joined.
Regards,
Piyush rai
Boiler PEM

VPN access required to Mr. Piyush Rai (Boiler PEM) for work through VPN.

@Isgec/dc-infra-team , Myself Praveen Kumar is working for creation account.

**Comment by msrawat-isgec** [comment]
Dear Mr. Piyush,

 

Needful is done. Please find the credential for access IT-Services through
VPN from outside office.

 

User Name:        3879

Password:           Welcome@123

 

You have to change password once you login first time.

 

@Helpdesk Team, Please configure accordingly and show to Mr. Piyush how to
access required IT-Services through VPN.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Piyush Rai [mailto:piyush.rai@isgec.co.in] 
Sent: 04 February 2021 11:18
To: praveen1.kumar@isgec.co.in
Subject: RE: READ & WRITE ACCESS(PIYUSH RAI EMP CODE-3879)

 

Dear Praveen,

 

Kindly let me have Accel Pro ID & Passoword for using the system from Home
Wi-fi. I have Newly Joined.

 

Regards,

Piyush rai

Boiler PEM

 

From: Piyush Rai [mailto:piyush.rai@isgec.co.in] 
Sent: Monday, February 1, 2021 8:46 AM
To: 'praveen1.kumar@isgec.co.in'
Cc: 'kvanguraju@isgec.co.in'
Subject: READ & WRITE ACCESS(PIYUSH RAI EMP CODE-3879)

 

Dear Praveen,

 

I have newly joined in Boiler PEM.

 

Pease Provide me READ & WRITE ACCESS to following folder.

 

1)     Ijt-design (\\192.168.25.26 <file:///\\192.168.25.26> )

2)     Ijt-design-doc (\\192.168.25.26 <file:///\\192.168.25.26> )

3)     common folder (\\192.168.7.192 <file:///\\192.168.7.192> )

4)     pem-esc (\\192.168.25.80 <file:///\\192.168.25.80> )

 

Regards,

Piyush Rai

Extn-1550
