### ISSUE TITLE
RVNL Kavi Subhas and RVNL Joka SItes - AccelPro VPN

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-VPN#5]
Please provide the Accel Pro ID and Password for following employees deputed at site:
1.	RVNL Kavi Subhas site (EC0032) – Mr. Sumeet Shankar (Emp Code – 3816)
2.	RVNL Joka site (EC0041) – Mr. Amit Ganguly (Emp Code – 10550)
3.	RVNL Joka site (EC0041) – Mr. Sanjeev Kumar Jha (Emp Code – 10560)
4.	RVNL Joka site (EC0041) – Mr. Pawan Kr. Upadhyay (Emp Code – 3854)
5.	RVNL Joka site (EC0041) – Mr. Subodha Kr. Sahu (Emp Code – 10448)

Regards,
Nilesh Sinha
EPC - Construction 
@Isgec/dc-infra-team  , Myself Praveen Kumar is working for the same.

**Comment by msrawat-isgec** [comment]
Dear Team,

 

VPN accounts are created for all below mentioned users. Derails as follows.

 

Below given password is temporarily for all users, must change password once
login first time. 

 


Sn

AccelPro Account

Password

User Name

Location


1

3816

Welcome@123

Sumeet Shankar

RVNL Kavi Subhash Site


2

10550

Welcome@123

Amit Ganguly

RVNL Joka Site


3

10560

Welcome@123

Sanjeev Kumar Jha

RVNL Joka Site


4

3854

Welcome@123

Pawan Kumar Upadhyay

RVNL Joka Site


5

10448

Welcome@123

Subodha Kumar Sahu

RVNL Joka Site

 

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Vinay Sharma [mailto:vinay.sharma@isgec.co.in] 
Sent: 26 February 2021 11:27
To: praveen1.kumar@isgec.co.in; 'Helpdesk'
Cc: supratim.dey@isgec.co.in; sushilkroy@isgec.co.in; 'Nilesh Sinha'
Subject: RE: Laptops for RVNL Kavi Subhas and RVNL Joka

 

Praveen  

 

Please do the needful and update immediately to helpdesk team for
configuration .

 

 

Regards

Vinay 

 

From: helpdesk.noida24-request@isgec.co.in
<helpdesk.noida24-request@isgec.co.in> On Behalf Of Nilesh Sinha
Sent: 26 February 2021 11:19
To: praveen1.kumar@isgec.co.in; Helpdesk <helpdesk.noida24@isgec.co.in>
Cc: supratim.dey@isgec.co.in; sushilkroy@isgec.co.in
Subject: RE: Laptops for RVNL Kavi Subhas and RVNL Joka

 

Dear Sir,

 

Please provide the Accel Pro ID and Password for following employees deputed
at site:

1.	RVNL Kavi Subhas site (EC0032) - Mr. Sumeet Shankar (Emp Code -
3816)
2.	RVNL Joka site (EC0041) - Mr. Amit Ganguly (Emp Code - 10550)
3.	RVNL Joka site (EC0041) - Mr. Sanjeev Kumar Jha (Emp Code - 10560)
4.	RVNL Joka site (EC0041) - Mr. Pawan Kr. Upadhyay (Emp Code - 3854)
5.	RVNL Joka site (EC0041) - Mr. Subodha Kr. Sahu (Emp Code - 10448)

 

Regards,

Nilesh Sinha

EPC - Construction 

Description: Description: Isgec eSign

A-4, Sec-24, Noida - 201301 (UP)

Mob: +91-7042219977

Email: nilesh.sinha@isgec.co.in

website: www.isgec.com <http://www.isgec.com/> 

 

From: Nilesh Sinha [mailto:nilesh.sinha@isgec.co.in] 
Sent: 25 February 2021 09:55
To: Helpdesk (helpdesk.noida24@isgec.co.in)
Cc: supratim.dey@isgec.co.in; sushilkroy@isgec.co.in
Subject: RE: Laptops for RVNL Kavi Subhas and RVNL Joka

 

Dear Sir,

 

Please configure and make ready all the laptops as mentioned in the trailing
mail by tomorrow 1st half as the same needs to be handed over tomorrow to
site staff.

Kindly install the basic software's along with Baan, accelpro, etc. in all
the laptops.

 

Regards,

Nilesh Sinha

EPC - Construction 

Description: Description: Isgec eSign

A-4, Sec-24, Noida - 201301 (UP)

Mob: +91-7042219977

Email: nilesh.sinha@isgec.co.in

website: www.isgec.com <http://www.isgec.com/> 

 

From: Nilesh Sinha [mailto:nilesh.sinha@isgec.co.in] 
Sent: 19 February 2021 14:37
To: Helpdesk (helpdesk.noida24@isgec.co.in)
Cc: supratim.dey@isgec.co.in; sushilkroy@isgec.co.in
Subject: RE: Laptops for RVNL Kavi Subhas and RVNL Joka

 

Dear Sir,

 

Following Laptops are to be issued as per the attached sanction.

1.	RVNL Kavi Subhas site (EC0032) - Mr. Sumeet Shankar (Emp Code -
3816)
2.	RVNL Joka site (EC0041) - Mr. Amit Ganguly (Emp Code - 10550)
3.	RVNL Joka site (EC0041) - Mr. Sanjeev Kumar Jha (Emp Code - 10560)
4.	RVNL Joka site (EC0041) - Mr. Pawan Kr. Upadhyay (Emp Code - 3854)
5.	RVNL Joka site (EC0041) - Mr. Subodha Kr. Sahu (Emp Code - 10448)

 

Request you to kindly install all the softwares, Accel Pro, Baan, Joomla,
etc.

 

Regards,

Nilesh Sinha

EPC - Construction 

Description: Description: Isgec eSign

A-4, Sec-24, Noida - 201301 (UP)

Mob: +91-7042219977

Email: nilesh.sinha@isgec.co.in

website: www.isgec.com <http://www.isgec.com/> 

 

From: Nilesh Sinha [mailto:nilesh.sinha@isgec.co.in] 
Sent: 31 December 2020 17:08
To: Helpdesk (helpdesk.noida24@isgec.co.in)
Cc: 'Sheetal Deshmukh' (sheetal.deshmukh@isgec.co.in); 'Anjani Kumar Rai '
(anjani.rai@isgec.co.in); supratim.dey@isgec.co.in
Subject: Laptops for RVNL Kavi Subhas and RITES Bongaigaon

 

Dear Sir,

 

Please find attached herewith the sanctions of laptop for RVNL Kavi Subhas
and RITES Bongaigaon which will be issued to following person.

1.	RVNL Kavi Subhas site (EC0032) - Mr. Sumeet Shankar (Emp Code -
3816)
2.	RITES Bongaigaon site (EC0024) - Mr. Pankaj Kumar Srivastava (Emp
Code - 10302)

 

Regards,

Nilesh Sinha

EPC - Construction 

Description: Description: Isgec eSign

A-4, Sec-24, Noida - 201301 (UP)

Mob: +91-7042219977

Email: nilesh.sinha@isgec.co.in

website: www.isgec.com <http://www.isgec.com/>
